### ISSUE TITLE
ssl-certificate search not working for 'serialNumber' field

### ISSUE THREAD

**Issue by gusdadiya-crest** [passivetotal/python_api#23]
This method "search_ssl_certificate_by_field" uses the endpoint "ssl-certificate/search" that takes 2 params "field" and "query" to fetch the result. It is mentioned in the official documentation that "serialNumber" is a valid field for the given endpoint. But when we pass "serialNumber" in the field and a valid value in the query(field value), it returns an empty result array which should not be the case as we can see the results for the same on the UI.

**Comment by aeetos** [comment]
Thanks for pointing this out. The problem seems to be related to the upstream API, and not this library code specifically. We created a ticket to track the issue through the official support channels for RiskIQ.
