### ISSUE TITLE
**kwargs usage may result in typos in keyword arguments being quietly ignored

### ISSUE THREAD

**Issue by johannestaas** [passivetotal/python_api#4]
`DnsRequest.from_config().get_passive_dns(query='netflix.com', source=['riskiq'])`

When a similar request is made, it goes through fine but source is mistakenly used instead of sources, so the keyword is ignored and data from all sources is returned.

Possible enhancement might be to either rewrite with keyword arguments explicitly stated in function declaration, or have kwargs checked against all possible keywords, erroring if extra unknown keywords exist.

Also possible to close and ignore and just make sure the documentation is very clear.

**Comment by aeetos** [comment]
Good feedback - going forward, we will introduce more explicit parameters to avoid this issue and make the code more self-documenting. You'll see some steps in that direction in an upcoming release.
