### ISSUE TITLE
Modify client output formats to remove recordHash from default output

### ISSUE THREAD

**Issue by dspruell** [passivetotal/python_api#5]
`pt-client pdns` response format can be improved by taking the _recordHash_ field out of the standard response output and maybe exposing it only through a _--verbose_ option or similar. The recordHash isn't import to most users most of the time and reduced record length will eliminate line wrapping in many cases. This field is currently returned in the _text_ output format.

**Comment by aeetos** [comment]
Good feedback - formatters have been mostly removed from the core codebase in an earlier version, so this is issue is no longer relevant.
