### ISSUE TITLE
Change query options to non-optional (positional params)

### ISSUE THREAD

**Issue by dspruell** [passivetotal/python_api#7]
In pt-client subcommands, a non-optional argument is implemented as a required command-line option:

```
usage: pt-client pdns [-h] --query QUERY [--sources SOURCES [SOURCES ...]]
                      [--end END] [--start START] [--timeout TIMEOUT]
                      [--unique] [--format {json,text,csv,stix,table,xml}]
...
  --query QUERY, -q QUERY
                        Query for a domain, IP address or wildcard
```

Since --query is not optional, it would be more sensible from usage convention standpoint to shift it to a positional parameter instead of required optional parameter (and also not require typing `-q` to invoke).

This is the case in multiple subcommands, suggest revising in all.

**Comment by aeetos** [comment]
Agreed this is more standard, but we're committed now - folks have likely written batch scripts to depend on this and we don't want to break them. Appreciate the suggestion.
